# Generated by Django 4.1.3 on 2023-03-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isPublish',
            field=models.BooleanField(default=False, verbose_name='Yayınla'),
        ),
    ]
