# Generated by Django 4.1.3 on 2023-03-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(default='profiles/default.jpg', null=True, upload_to='profiles/', verbose_name='Profil Resmi'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Merhaba ben bir blog yazarıyım.', max_length=500, verbose_name='Hakkımda'),
        ),
    ]
