# Generated by Django 4.1.3 on 2023-03-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_profile_follow_profile_takip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='takip',
        ),
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='takipciler', to='user.profile', verbose_name='Takipçiler'),
        ),
    ]
